# 4.8 Grouping data and aggregating variables

### This script contains the following points:

#### 1. Create crosstab for final from merged data
#### 2. Creating a loyalty flag for customers
#### 3. Creating a spending flag for customers
#### 4. Creating an order frequency flag for customers

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Path import

path = r'/Users/nekow/Documents/Instacart Basket Analysis'

In [3]:
# Importing pickle file

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_analysis.pkl'))

In [4]:
# Grouping the products

ords_prods_merge.groupby('product_name')

## 1. Create crosstab for final from merged data

In [5]:
crosstab = pd.crosstab(ords_prods_merge['days_since_prior_order'], ords_prods_merge['order_number'], dropna = False)

In [6]:
crosstab.to_clipboard()

In [5]:
# Splitting the data into groups


ords_prods_merge.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Step 3 of Exercise 4.8
The entire dataframe has an ordered numerical organization rather than that of the set with only part of the dataframe.

In [6]:
# Producing the mean, min, and max

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.457838   1  99
2                17.277920   1  99
3                17.170395   1  99
4                17.811403   1  99
5                15.215751   1  99
6                16.439806   1  99
7                17.225802   1  99
8                15.340650   1  99
9                15.895474   1  99
10               20.197148   1  99
11               16.170638   1  99
12               15.887671   1  99
13               16.583536   1  99
14               16.773669   1  99
15               16.165037   1  99
16               17.665606   1  99
17               15.694469   1  99
18               19.310397   1  99
19               17.177343   1  99
20               16.473447   1  99
21               22.902379   1  99

In [7]:
ords_prods_merge.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range,price_range_loc,Busiest_days,busiest_period_of_day
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Mid-range product,Average Days,Most orders
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Mid-range product,Average Days,Average orders
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Mid-range product,Busiest days,Average orders
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Mid-range product,Slowest days,Most orders
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Mid-range product,Slowest days,Average orders

In [8]:
# dropping unnecessary columns

ords_prods_merge = ords_prods_merge.drop(columns = ['price_range_loc'])

In [9]:
# Splitting the data into user_id columns

ords_prods_merge.groupby('user_id').agg({'order_number': ['max']})

        order_number
                 max
user_id
1                 10
2                 14
3                 12
4                  5
5                  4
...              ...
206205             3
206206            67
206207            16
206208            49
206209            13

[206209 rows x 1 columns]

### Step 4 of Exercise 4.8

In [10]:
# max order creation

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/hs/djjm__mn4d33wxms4t4q0flh0000gp/T/ipykernel_5243/602137744.py:3: FutureWarning: The provided callable <function amax at 0x1131d0fe0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
# data check for 15

ords_prods_merge.head(15)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range,Busiest_days,busiest_period_of_day,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Average Days,Most orders,32
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Average Days,Average orders,32
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Average orders,26
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,14,30.0,2,0,both,Mid-range product,Average Days,Most orders,9
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,10,30.0,1,0,both,Mid-range product,Slowest days,Most orders,12
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,20,19.0,1,0,both,Mid-range product,Busiest days,Average orders,20
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,12,15.0,2,1,both,Mid-range product,Busiest days,Most orders,20
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,11,NaN,1,0,both,Mid-range product,Average Days,Most orders,10
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,13,7.0,1,0,both,Mid-range product,Slowest days,Most orders,43
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,13,7.0,3,1,both,Mid-range product,Slowest days,Most orders,43
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,12,12.0,4,1,both,Mid-range product,Average Days,Most orders,43
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,10,2.0,8,0,both,Mid-range product,Slowest days,Most orders,13

In [12]:
# removing limiters

pd.options.display.max_rows = None

In [13]:
# checking 100 columns

ords_prods_merge.head(100)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range,Busiest_days,busiest_period_of_day,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Average Days,Most orders,32
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Average Days,Average orders,32
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Average orders,26
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,14,30.0,2,0,both,Mid-range product,Average Days,Most orders,9
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,10,30.0,1,0,both,Mid-range product,Slowest days,Most orders,12
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,20,19.0,1,0,both,Mid-range product,Busiest days,Average orders,20
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,12,15.0,2,1,both,Mid-range product,Busiest days,Most orders,20
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,11,NaN,1,0,both,Mid-range product,Average Days,Most orders,10
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,13,7.0,1,0,both,Mid-range product,Slowest days,Most orders,43
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,13,7.0,3,1,both,Mid-range product,Slowest days,Most orders,43
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,12,12.0,4,1,both,Mid-range product,Average Days,Most orders,43
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,10,2.0,8,0,both,Mid-range product,Slowest days,Most orders,13
15,0,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,prior,7,2,8,6.0,18,1,both,Mid-range product,Average Days,Average orders,13
16,0,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,prior,9,5,8,10.0,12,1,both,Mid-range product,Average Days,Average orders,13
17,0,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,prior,4,2,0,7.0,10,0,both,Mid-range product,Average Days,Fewest orders,28
18,0,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,21,6.0,9,1,both,Mid-range product,Busiest days,Average orders,28
19,0,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,prior,6,1,0,14.0,9,1,both,Mid-range product,Busiest days,Fewest orders,28
20,0,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,prior,7,2,2,8.0,7,1,both,Mid-range product,Average Days,Fewest orders,28
21,0,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,prior,8,1,23,6.0,6,1,both,Mid-range product,Busiest days,Fewest orders,28
22,0,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,prior,9,1,3,28.0,6,1,both,Mid-range product,Busiest days,Fewest orders,28
23,0,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,prior,14,1,14,7.0,10,1,both,Mid-range product,Busiest days,Most orders,28
24,0,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,prior,15,1,14,7.0,3,1,both,Mid-range product,Busiest days,Most orders,28
25,0,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,prior,18,0,21,0.0,5,1,both,Mid-range product,Busiest days,Average orders,28
26,0,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,prior,19,0,22,7.0,11,1,both,Mid-range product,Busiest days,Average orders,28
27,0,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,prior,20,0,22,7.0,11,1,both,Mid-range product,Busiest days,Average orders,28
28,0,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,prior,21,0,20,7.0,5,1,both,Mid-range product,Busiest days,Average orders,28
29,0,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,prior,22,0,22,7.0,15,1,both,Mid-range product,Busiest days,Average orders,28
30,0,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,prior,24,4,22,3.0,4,1,both,Mid-range product,Slowest days,Average orders,28
31,0,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,prior,25,6,19,16.0,6,1,both,Mid-range product,Average Days,Average orders,28
32,0,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,prior,27,1,1,5.0,1,1,both,Mid-range product,Busiest days,Fewest orders,28
33,0,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,prior,28,0,21,6.0,1,1,both,Mid-range product,Busiest days,Average orders,28
34,0,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,prior,1,2,12,NaN,2,0,both,Mid-range product,Average Days,Most orders,4
35,0,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,prior,2,2,10,21.0,2,1,both,Mid-range product,Average Days,Most orders,4
36,0,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,prior,3,4,17,2.0,3,1,both,Mid-range product,Slowest days,Average orders,4
37,0,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,prior,1,1,9,NaN,1,0,both,Mid-range product,Busiest days,Most orders,10
38,0,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,prior,4,0,13,18.0,6,1,both,Mid-range product,Busiest days,Most orders,10
39,0,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,prior,6,1,9,8.0,3,1,both,Mid-range product,Busiest days,Most orders,10
40,0,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,prior,8,0,17,30.0,10,1,both,Mid-range product,Busiest days,Average orders,10
41,0,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,prior,9,4,15,25.0,1,1,both,Mid-range product,Slowest days,Most orders,10
42,0,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,prior,1,0,14,NaN,12,0,both,Mid-range product,Busiest days,Most orders,10
43,0,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,prior,7,1,16,9.0,10,0,both,Mid-range product,Busiest days,Most orders,23
44,0,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,prior,24,1,8,10.0,5,0,both,Mid-range product,Busiest days,Average orders,25
45,0,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,prior,5,3,10,7.0,11,0,both,Mid-range product,Slowest days,Most orders,13
46,0,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,prior,1,2,20,NaN,8,0,both,Mid-range product,Average Days,Average orders,5
47,0,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,prior,4,2,10,30.0,7,0,both,Mid-range product,Average Days,Most orders,6
48,0,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,prior,1,1,14,NaN,2,0,both,Mid-range product,Busiest days,Most orders,3
49,0,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,prior,2,1,10,7.0,8,0,both,Mid-range product,Busiest days,Most orders,42
50,0,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,prior,3,1,10,7.0,2,1,both,Mid-range product,Busiest days,Most orders,42
51,0,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,prior,5,3,13,7.0,6,1,both,Mid-range product,Slowest days,Most orders,42
52,0,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,prior,9,2,11,5.0,3,1,both,Mid-range product,Average Days,Most orders,42
53,0,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,prior,12,1,11,4.0,2,1,both,Mid-range product,Busiest days,Most orders,42
54,0,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,prior,11,2,7,8.0,1,0,both,Mid-range product,Average Days,Average orders,40
55,0,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,prior,2,0,8,30.0,2,0,both,Mid-range product,Busiest days,Average orders,9
56,0,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,prior,1,1,16,NaN,9,0,both,Mid-range product,Busiest days,Most orders,4
57,0,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,prior,3,5,16,29.0,1,0,both,Mid-range product,Average Days,Most orders,4
58,0,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,prior,6,0,13,12.0,7,0,both,Mid-range product,Busiest days,Most orders,14
59,0,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,prior,1,4,15,NaN,11,0,both,Mid-range product,Slowest days,Most orders,6
60,0,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,prior,5,2,23,4.0,6,0,both,Mid-range product,Average Days,Fewest orders,8
61,0,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,prior,3,3,15,5.0,5,0,both,Mid-range product,Slowest days,Most orders,21
62,0,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,prior,4,1,17,5.0,6,1,both,Mid-range product,Busiest days,Average orders,21
63,0,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,prior,20,1,8,13.0,3,1,both,Mid-range product,Busiest days,Average orders,21
64,0,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,prior,9,2,15,10.0,2,0,both,Mid-range product,Average Days,Most orders,31
65,0,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,prior,13,0,23,6.0,1,1,both,Mid-range product,Busiest days,Fewest orders,31
66,0,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,prior,14,2,23,9.0,1,1,both,Mid-range product,Average Days,Fewest orders,31
67,0,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,prior,24,2,13,6.0,2,1,both,Mid-range product,Average Days,Most orders,31
68,0,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,prior,30,3,16,8.0,2,1,both,Mid-range product,Slowest days,Most orders,31
69,0,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,prior,34,4,13,1.0,13,0,both,Mid-range product,Slowest days,Most orders,99
70,0,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,prior,4,3,10,7.0,2,0,both,Mid-range product,Slowest days,Most orders,36
71,0,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,prior,8,4,11,21.0,2,0,both,Mid-range product,Slowest days,Most orders,9
72,0,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,prior,2,0,12,30.0,2,0,both,Mid-range product,Busiest days,Most orders,5
73,0,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,prior,3,3,13,30.0,1,1,both,Mid-range product,Slowest days,Most orders,5
74,0,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,prior,1,0,17,NaN,11,0,both,Mid-range product,Busiest days,Average orders,5
75,0,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,prior,2,0,17,30.0,3,0,both,Mid-range product,Busiest days,Average orders,23
76,0,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,prior,4,4,18,8.0,2,1,both,Mid-range product,Slowest days,Average orders,23
77,0,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,prior,5,4,15,7.0,1,1,both,Mid-range product,Slowest days,Most orders,23
78,0,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,prior,6,4,21,14.0,2,1,both,Mid-range product,Slowest days,Average orders,23
79,0,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,prior,7,4,18,28.0,1,1,both,Mid-range product,Slowest days,Average orders,23
80,0,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,prior,10,4,7,16.0,4,1,both,Mid-range product,Slowest days,Average orders,23
81,0,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,prior,14,4,22,1.0,1,1,both,Mid-range product,Slowest days,Average orders,23
82,0,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,prior,15,4,16,14.0,1,1,both,Mid-range product,Slowest days,Most orders,23
83,0,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,prior,16,4,15,7.0,2,1,both,Mid-range product,Slowest days,Most orders,23
84,0,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,prior,20,4,13,8.0,1,1,both,Mid-range product,Slowest days,Most orders,23
85,0,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,prior,22,4,14,16.0,7,1,both,Mid-range product,Slowest days,Most orders,23
86,0,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,prior,17,4,18,8.0,16,0,both,Mid-range product,Slowest days,Average orders,23
87,0,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,prior,6,4,18,14.0,5,0,both,Mid-range product,Slowest days,Average orders,11
88,0,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,prior,1,0,16,NaN,2,0,both,Mid-range product,Busiest days,Most orders,5
89,0,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,prior,22,1,16,8.0,8,0,both,Mid-range product,Busiest days,Most orders,22
90,0,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,prior,4,2,14,14.0,15,0,both,Mid-range product,Average Days,Most orders,21
91,0,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,prior,8,2,14,14.0,9,1,both,Mid-range product,Average Days,Most orders,21
92,0,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,prior,10,0,21,10.0,1,0,both,Mid-range product,Busiest days,Average orders,36
93,0,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,prior,11,0,19,14.0,4,1,both,Mid-range product,Busiest days,Average orders,36
94,0,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,prior,16,2,16,4.0,2,1,both,Mid-range product,Average Days,Most orders,36
95,0,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,prior,8,3,11,23.0,5,0,both,Mid-range product,Slowest days,Most orders,10
96,0,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,prior,18,1,14,30.0,1,0,both,Mid-range product,Busiest days,Most orders,23
97,0,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,prior,13,5,16,2.0,8,0,both,Mid-range product,Average Days,Most orders,26
98,0,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,prior,16,3,13,0.0,2,0,both,Mid-range product,Slowest days,Most orders,43
99,0,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,prior,10,2,15,3.0,6,0,both,Mid-range product,Average Days,Most orders,21

In [14]:
# Dropping the unnamed columns

ords_prods_merge = ords_prods_merge.drop(columns = ['Unnamed: 0'])

## 2. Creating a loyalty flag for customers

In [15]:
# max order for loyal customers

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

/var/folders/hs/djjm__mn4d33wxms4t4q0flh0000gp/T/ipykernel_5243/430384142.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Loyal customer' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [16]:
# max order for regular customers

ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [17]:
# max order for new customers

ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
# value count for loyalty flag creation

ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [19]:
# Confirmation of loyalty flag creation

ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(15)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6

In [20]:
# Loyalty flag for customer spending habits basic statistics

ords_prods_merge.groupby('loyalty_flag').agg({'prices' : ['mean','min','max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

### Step 5 of Exercise 4.8
The mean suggests that New Customers spend more on average than any other customers, and Loyal Customers spend an average lower than even Regular Customers. All customers spend a lowest amount of 1 and a maximum amount of 99,999.

## 3. Creating a spending flag for customers

### Step 6 of Exercise 4.8

In [21]:
# column reation for the mean of prices

ords_prods_merge['mean_prices'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

/var/folders/hs/djjm__mn4d33wxms4t4q0flh0000gp/T/ipykernel_5243/1060439922.py:3: FutureWarning: The provided callable <function mean at 0x1131d1d00> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['mean_prices'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [22]:
# Data check

ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,...,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,...,3.0,5,0,both,Mid-range product,Average Days,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,...,20.0,1,1,both,Mid-range product,Average Days,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,...,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,...,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,...,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3,New customer,4.972414
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,...,26.0,7,0,both,Mid-range product,Busiest days,Average orders,26,Regular customer,6.935398
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,...,30.0,2,0,both,Mid-range product,Average Days,Most orders,9,New customer,5.957576
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,...,30.0,1,0,both,Mid-range product,Slowest days,Most orders,12,Regular customer,6.680000
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,...,19.0,1,0,both,Mid-range product,Busiest days,Average orders,20,Regular customer,7.162500
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,...,15.0,2,1,both,Mid-range product,Busiest days,Most orders,20,Regular customer,7.162500
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,...,NaN,1,0,both,Mid-range product,Average Days,Most orders,10,New customer,5.813636
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,...,7.0,1,0,both,Mid-range product,Slowest days,Most orders,43,Loyal customer,5.081633
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,...,7.0,3,1,both,Mid-range product,Slowest days,Most orders,43,Loyal customer,5.081633
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,...,12.0,4,1,both,Mid-range product,Average Days,Most orders,43,Loyal customer,5.081633
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,...,2.0,8,0,both,Mid-range product,Slowest days,Most orders,13,Regular customer,6.803797

In [23]:
# Low spender indicator

ords_prods_merge.loc[ords_prods_merge['mean_prices'] < 10, 'spending_flag'] = 'Low spender'

/var/folders/hs/djjm__mn4d33wxms4t4q0flh0000gp/T/ipykernel_5243/2461071344.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Low spender' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  ords_prods_merge.loc[ords_prods_merge['mean_prices'] < 10, 'spending_flag'] = 'Low spender'

In [24]:
# High spender indicator

ords_prods_merge.loc[ords_prods_merge['mean_prices'] >= 10, 'spending_flag'] = 'High spender'

In [25]:
# flag consistenct check

ords_prods_merge[['user_id', 'spending_flag', 'product_id']].head(15)

    user_id spending_flag  product_id
0       138   Low spender           1
1       138   Low spender           1
2       709   Low spender           1
3       764   Low spender           1
4       764   Low spender           1
5       777   Low spender           1
6       825   Low spender           1
7       910   Low spender           1
8      1052   Low spender           1
9      1052   Low spender           1
10     1379   Low spender           1
11     1480   Low spender           1
12     1480   Low spender           1
13     1480   Low spender           1
14     1494   Low spender           1

In [26]:
# Value count for spending flag

ords_prods_merge['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

## 4. Creating an order frequency flag for customers

### Step 7 of Exercise 4.8

In [27]:
# median order frequency creation

ords_prods_merge['median_order_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

/var/folders/hs/djjm__mn4d33wxms4t4q0flh0000gp/T/ipykernel_5243/2457283246.py:3: FutureWarning: The provided callable <function median at 0x1133200e0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['median_order_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [28]:
# data check

ords_prods_merge.tail(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,...,reordered,_merge,price_range,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices,spending_flag,median_order_frequency
32404844,49688,Fresh Foaming Cleanser,73,11,13.5,1173882,178752,prior,7,0,...,0,both,NaN,Busiest days,Fewest orders,16,Regular customer,8.643223,Low spender,21.0
32404845,49688,Fresh Foaming Cleanser,73,11,13.5,1525694,178752,prior,15,5,...,1,both,NaN,Average Days,Most orders,16,Regular customer,8.643223,Low spender,21.0
32404846,49688,Fresh Foaming Cleanser,73,11,13.5,2439069,182948,prior,4,6,...,0,both,NaN,Average Days,Most orders,8,New customer,7.306667,Low spender,16.0
32404847,49688,Fresh Foaming Cleanser,73,11,13.5,2392655,182948,prior,8,2,...,1,both,NaN,Average Days,Most orders,8,New customer,7.306667,Low spender,16.0
32404848,49688,Fresh Foaming Cleanser,73,11,13.5,848810,183548,prior,15,2,...,0,both,NaN,Average Days,Most orders,15,Regular customer,8.340659,Low spender,9.0
32404849,49688,Fresh Foaming Cleanser,73,11,13.5,2251059,184081,prior,1,6,...,0,both,NaN,Average Days,Most orders,11,Regular customer,7.684426,Low spender,12.0
32404850,49688,Fresh Foaming Cleanser,73,11,13.5,846716,187523,prior,14,3,...,0,both,NaN,Slowest days,Most orders,17,Regular customer,7.812676,Low spender,16.0
32404851,49688,Fresh Foaming Cleanser,73,11,13.5,362546,188073,prior,5,2,...,0,both,NaN,Average Days,Fewest orders,31,Regular customer,6.058416,Low spender,8.0
32404852,49688,Fresh Foaming Cleanser,73,11,13.5,3166828,188073,prior,7,1,...,1,both,NaN,Busiest days,Most orders,31,Regular customer,6.058416,Low spender,8.0
32404853,49688,Fresh Foaming Cleanser,73,11,13.5,3106363,197371,prior,10,4,...,0,both,NaN,Slowest days,Most orders,10,New customer,8.814508,Low spender,4.0
32404854,49688,Fresh Foaming Cleanser,73,11,13.5,1788356,200215,prior,2,0,...,0,both,NaN,Busiest days,Most orders,6,New customer,8.220313,Low spender,7.0
32404855,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,prior,1,4,...,0,both,NaN,Slowest days,Most orders,4,New customer,7.364516,Low spender,30.0
32404856,49688,Fresh Foaming Cleanser,73,11,13.5,809510,200873,prior,5,3,...,0,both,NaN,Slowest days,Average orders,20,Regular customer,8.500344,Low spender,6.0
32404857,49688,Fresh Foaming Cleanser,73,11,13.5,2359893,200873,prior,9,3,...,1,both,NaN,Slowest days,Most orders,20,Regular customer,8.500344,Low spender,6.0
32404858,49688,Fresh Foaming Cleanser,73,11,13.5,2385091,205926,prior,11,1,...,0,both,NaN,Busiest days,Most orders,11,Regular customer,8.133333,Low spender,6.0

In [29]:
# median order for median frequency on non-frequent customers

ords_prods_merge.loc[ords_prods_merge['median_order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

/var/folders/hs/djjm__mn4d33wxms4t4q0flh0000gp/T/ipykernel_5243/1100560102.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Non-frequent customer' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  ords_prods_merge.loc[ords_prods_merge['median_order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [30]:
# median order for median frequency on regular customers

ords_prods_merge.loc[(ords_prods_merge['median_order_frequency'] > 10) & (ords_prods_merge['median_order_frequency'] <= 20), 'order_frequency_flag'] = 'Regular customer'

In [31]:
# median order for median frequency on frequent customers

ords_prods_merge.loc[ords_prods_merge['median_order_frequency'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [32]:
# Value count for order frequency flag

ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

order_frequency_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: count, dtype: int64

In [33]:
# finding the missing values for the new flag

ords_prods_merge[ords_prods_merge['order_frequency_flag'].isnull() == True]

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,...,_merge,price_range,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices,spending_flag,median_order_frequency,order_frequency_flag
6234909,10749,Organic Red Bell Pepper,83,4,5.7,895835,159838,prior,1,0,...,both,NaN,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
12947653,21334,Organic Peeled Garlic,123,4,10.2,895835,159838,prior,1,0,...,both,NaN,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
13839012,22198,4X Ultra Concentrated Natural Laundry Detergen...,75,17,1.7,895835,159838,prior,1,0,...,both,NaN,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
14758536,23695,California Veggie Burger,42,1,4.7,895835,159838,prior,1,0,...,both,NaN,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
21673807,33401,Goat Cheese Crumbles,21,16,14.8,895835,159838,prior,1,0,...,both,NaN,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN

### There's a customer anomaly for 5 variables where they are a new customer with no prior purchases that doesn't fit the criteria for any frequency flags.

In [34]:
# data check

ords_prods_merge.tail(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,...,_merge,price_range,Busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices,spending_flag,median_order_frequency,order_frequency_flag
32404844,49688,Fresh Foaming Cleanser,73,11,13.5,1173882,178752,prior,7,0,...,both,NaN,Busiest days,Fewest orders,16,Regular customer,8.643223,Low spender,21.0,Non-frequent customer
32404845,49688,Fresh Foaming Cleanser,73,11,13.5,1525694,178752,prior,15,5,...,both,NaN,Average Days,Most orders,16,Regular customer,8.643223,Low spender,21.0,Non-frequent customer
32404846,49688,Fresh Foaming Cleanser,73,11,13.5,2439069,182948,prior,4,6,...,both,NaN,Average Days,Most orders,8,New customer,7.306667,Low spender,16.0,Regular customer
32404847,49688,Fresh Foaming Cleanser,73,11,13.5,2392655,182948,prior,8,2,...,both,NaN,Average Days,Most orders,8,New customer,7.306667,Low spender,16.0,Regular customer
32404848,49688,Fresh Foaming Cleanser,73,11,13.5,848810,183548,prior,15,2,...,both,NaN,Average Days,Most orders,15,Regular customer,8.340659,Low spender,9.0,Frequent customer
32404849,49688,Fresh Foaming Cleanser,73,11,13.5,2251059,184081,prior,1,6,...,both,NaN,Average Days,Most orders,11,Regular customer,7.684426,Low spender,12.0,Regular customer
32404850,49688,Fresh Foaming Cleanser,73,11,13.5,846716,187523,prior,14,3,...,both,NaN,Slowest days,Most orders,17,Regular customer,7.812676,Low spender,16.0,Regular customer
32404851,49688,Fresh Foaming Cleanser,73,11,13.5,362546,188073,prior,5,2,...,both,NaN,Average Days,Fewest orders,31,Regular customer,6.058416,Low spender,8.0,Frequent customer
32404852,49688,Fresh Foaming Cleanser,73,11,13.5,3166828,188073,prior,7,1,...,both,NaN,Busiest days,Most orders,31,Regular customer,6.058416,Low spender,8.0,Frequent customer
32404853,49688,Fresh Foaming Cleanser,73,11,13.5,3106363,197371,prior,10,4,...,both,NaN,Slowest days,Most orders,10,New customer,8.814508,Low spender,4.0,Frequent customer
32404854,49688,Fresh Foaming Cleanser,73,11,13.5,1788356,200215,prior,2,0,...,both,NaN,Busiest days,Most orders,6,New customer,8.220313,Low spender,7.0,Frequent customer
32404855,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,prior,1,4,...,both,NaN,Slowest days,Most orders,4,New customer,7.364516,Low spender,30.0,Non-frequent customer
32404856,49688,Fresh Foaming Cleanser,73,11,13.5,809510,200873,prior,5,3,...,both,NaN,Slowest days,Average orders,20,Regular customer,8.500344,Low spender,6.0,Frequent customer
32404857,49688,Fresh Foaming Cleanser,73,11,13.5,2359893,200873,prior,9,3,...,both,NaN,Slowest days,Most orders,20,Regular customer,8.500344,Low spender,6.0,Frequent customer
32404858,49688,Fresh Foaming Cleanser,73,11,13.5,2385091,205926,prior,11,1,...,both,NaN,Busiest days,Most orders,11,Regular customer,8.133333,Low spender,6.0,Frequent customer

In [35]:
# flag consistenct check

ords_prods_merge[['user_id','order_frequency_flag','median_order_frequency']].head(15)

    user_id order_frequency_flag  median_order_frequency
0       138    Frequent customer                     8.0
1       138    Frequent customer                     8.0
2       709    Frequent customer                     8.0
3       764    Frequent customer                     9.0
4       764    Frequent customer                     9.0
5       777     Regular customer                    11.0
6       825     Regular customer                    20.0
7       910    Frequent customer                     6.0
8      1052    Frequent customer                    10.0
9      1052    Frequent customer                    10.0
10     1379     Regular customer                    20.0
11     1480    Frequent customer                     7.0
12     1480    Frequent customer                     7.0
13     1480    Frequent customer                     7.0
14     1494    Frequent customer                     7.0

In [ ]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_flagged.pkl'))